export const chains = [
  {
    id: 'ethereum',
    name: 'Ethereum',
    rpcUrl: 'https://ethereum-rpc.publicnode.com',
    denom: 'ETH',
    symbol: 'ETH',
    decimals: 18,
    image: '/path/to/ethereum.png',
  },
  {
    id: 'base',
    name: 'Base',
    rpcUrl: 'https://mainnet.base.org',
    denom: 'BASE',
    symbol: 'BASE',
    decimals: 18,
    image: '/chains/axelar.png',
  },
  {
    id: 'cosmoshub',
    name: 'Cosmos Hub',
    rpcUrl: 'https://rpc.cosmos.network',
    denom: 'ATOM',
    symbol: 'ATOM',
    decimals: 6,
    image: '/chains/axelar.png',
  },
  {
    id: 'axelar',
    name: 'Axelar',
    rpcUrl: 'https://rpc.axelar.network', 
    denom: 'AXL', 
    symbol: 'AXL', 
    decimals: 18, 
    image: '/chains/axelar.png',
  },
  {
    id: 'optimism',
    name: 'Optimism',
    rpcUrl: 'https://optimism-rpc.publicnode.com',
    denom: 'ETH',
    symbol: 'ETH',
    decimals: 18,
    image: '/path/to/optimism.png',
  }  
];
